apiVersion: v1
kind: ServiceAccount
metadata:
  name: ols-byok-pipeline-sa
  namespace: ${NAMESPACE}
imagePullSecrets:
  - name: redhat-registry-pull-secret
secrets:
  - name: redhat-registry-pull-secret
  - name: registry-push-secret
